# Generated by Django 5.0.6 on 2024-06-28 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('round', models.SmallIntegerField()),
                ('result', models.CharField(max_length=32)),
                ('w_p_rank', models.CharField(max_length=32, null=True)),
                ('b_p_rank', models.CharField(max_length=32, null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='go_games.event')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='black_payer_id', to='go_games.player')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='white_payer_id', to='go_games.player')),
            ],
        ),
    ]
