# Generated by Django 5.0.6 on 2024-07-04 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('round', models.SmallIntegerField()),
                ('result', models.CharField(max_length=32)),
                ('w_p_rank', models.CharField(max_length=32, null=True)),
                ('b_p_rank', models.CharField(max_length=32, null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='go_games.event')),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='black_payer_id', to='go_games.player')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='white_payer_id', to='go_games.player')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_move', models.IntegerField()),
                ('color', models.CharField(max_length=1)),
                ('position', models.CharField(max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='go_games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Tsumego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_desc', models.JSONField()),
                ('description', models.TextField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('ELM', 'Elementary'), ('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=3, null=True)),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
