# Generated by Django 5.0.6 on 2024-06-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsumego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_desc', models.JSONField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('ELM', 'Elementary'), ('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=3)),
            ],
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_move', models.IntegerField()),
                ('color', models.CharField(max_length=1)),
                ('position', models.CharField(max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go_games.game')),
            ],
        ),
    ]
