# Generated by Django 5.0.6 on 2024-07-10 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsumego',
            name='description',
            field=models.TextField(default=django.db.models.deletion.SET_NULL, null=True),
        ),
    ]
