# Generated by Django 5.0.6 on 2024-07-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_games', '0002_alter_tsumego_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsumego',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
