# Generated by Django 5.0.6 on 2024-06-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_games', '0002_tsumego_rename_games_game_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsumego',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
