# Generated by Django 5.0.6 on 2024-06-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_games', '0003_alter_tsumego_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsumego',
            name='difficulty',
            field=models.CharField(choices=[('ELM', 'Elementary'), ('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], max_length=3, null=True),
        ),
    ]
